apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose-kafka
    kompose.version: 1.21.0 (992df58d8)
  creationTimestamp: null
  labels:
    io.kompose.service: kafka-connector-mysql
  name: kafka-connector-mysql
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: kafka-connector-mysql
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f docker-compose-kafka
        kompose.version: 1.21.0 (992df58d8)
      creationTimestamp: null
      labels:
        io.kompose.service: kafka-connector-mysql
    spec:
      containers:
      - env:
        - name: CONNECT_BOOTSTRAP_SERVERS
          value: kafka:29092
        - name: CONNECT_CONFIG_STORAGE_REPLICATION_FACTOR
          value: "1"
        - name: CONNECT_CONFIG_STORAGE_TOPIC
          value: quickstart-avro-config
        - name: CONNECT_GROUP_ID
          value: quickstart-avro
        - name: CONNECT_INTERNAL_KEY_CONVERTER
          value: org.apache.kafka.connect.json.JsonConverter
        - name: CONNECT_INTERNAL_VALUE_CONVERTER
          value: org.apache.kafka.connect.json.JsonConverter
        - name: CONNECT_KEY_CONVERTER
          value: org.apache.kafka.connect.json.JsonConverter
        - name: CONNECT_LOG4J_ROOT_LOGLEVEL
          value: DEBUG
        - name: CONNECT_OFFSET_STORAGE_REPLICATION_FACTOR
          value: "1"
        - name: CONNECT_OFFSET_STORAGE_TOPIC
          value: quickstart-avro-offsets
        - name: CONNECT_PLUGIN_PATH
          value: /usr/share/java,/etc/kafka-connect/jars
        - name: CONNECT_REST_ADVERTISED_HOST_NAME
          value: localhost
        - name: CONNECT_REST_PORT
          value: "28083"
        - name: CONNECT_STATUS_STORAGE_REPLICATION_FACTOR
          value: "1"
        - name: CONNECT_STATUS_STORAGE_TOPIC
          value: quickstart-avro-status
        - name: CONNECT_VALUE_CONVERTER
          value: org.apache.kafka.connect.json.JsonConverter
        image: confluentinc/cp-kafka-connect:latest
        imagePullPolicy: ""
        name: kafka-connector-mysql
        ports:
        - containerPort: 28083
        resources: {}
        volumeMounts:
        - mountPath: /etc/kafka-connect/jars
          name: kafka-connector-mysql-claim0
      restartPolicy: Always
      serviceAccountName: ""
      volumes:
      - name: kafka-connector-mysql-claim0
        persistentVolumeClaim:
          claimName: kafka-connector-mysql-claim0
status: {}
