apiVersion: apps/v1
kind: Deployment
metadata:
  name: webserver-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      run: webserver
  template:
    metadata:
      labels:
        run: webserver
    spec:
      containers:
      - name: webserver
        command: ['python', '/server/run.py']
        # command: ['sleep', '6000']
        image: veev23/flask-server:1.0
        volumeMounts:
          - name: webserver-code
            mountPath: /server
        ports:
        - containerPort: 8000
      volumes:
        - name: webserver-code
          hostPath:
            path: /coding-genius-class-project/web_server
