apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose-kafka
    kompose.version: 1.21.0 (992df58d8)
  creationTimestamp: null
  labels:
    io.kompose.service: zookeeper
  name: zookeeper
spec:
  ports:
  - name: "32181"
    port: 32181
    targetPort: 32181
  selector:
    io.kompose.service: zookeeper
status:
  loadBalancer: {}
