apiVersion: v1
kind: Service
metadata:
  creationTimestamp: "2021-04-25T08:02:27Z"
  name: recommand-api-server-service
  namespace: default
  resourceVersion: "199577"
  uid: 9ea91538-8ba4-4384-b996-8558c3349f0c
spec:
  ports:
  - port: 15003
    protocol: TCP
    targetPort: 15003
  selector:
    run: webserver
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
