apiVersion: apps/v1
kind: Deployment
metadata:
  name: webserver-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      run: webserver
  template:
    metadata:
      labels:
        run: webserver
    spec:
      containers:
      - name: webserver
        env: 
        - name: RUN_FILE
          value: "/server/coding-genius-class-project.git/web_server/run.py"
        image: veev23/flask-server:2.0
        imagePullPolicy: Always
        volumeMounts:
          - name: git-volume
            mountPath: "/server"
        ports:
        - containerPort: 15000
      - name: loginserver
        env:
        - name: RUN_FILE
          value: "/server/coding-genius-class-project.git/login_server/run.py"
        image: veev23/flask-server:2.0
        imagePullPolicy: Always
        volumeMounts:
          - name: git-volume
            mountPath: "/server"
        ports:
        - containerPort: 15001
      - name: stockserver
        env:
        - name: RUN_FILE
          value: "/server/coding-genius-class-project.git/stock_server/run.py"
        image: veev23/flask-server:2.0
        imagePullPolicy: Always
        volumeMounts:
          - name: git-volume
            mountPath: "/server"
        ports:
        - containerPort: 15002

      - name: recommandserver
        env:
        - name: RUN_FILE
          value: "/server/coding-genius-class-project.git/recommand_server/run.py"
        image: veev23/flask-server:2.0
        imagePullPolicy: Always
        volumeMounts:
          - name: git-volume
            mountPath: "/server"
        ports:
        - containerPort: 15003

      - name: git-sync
        image: k8s.gcr.io/git-sync:v3.1.1
        env:
        - name: GIT_SYNC_REPO                 # git sync할 리모트 저장소
          value: https://github.com/veev13/coding-genius-class-project.git
        - name: GIT_SYNC_BRANCH               # target branch
          value: develop
        - name: GIT_SYNC_ROOT                 # 로컬 디렉토리 위치
          value: "/git"
        volumeMounts:
        - name: git-volume
          mountPath: "/git"
      volumes:
        - name: git-volume
          emptyDir: {}
